---
repos:
  - repo: local
    hooks:
      - id: uv-sync
        name: uv-sync
        description: install UV dependencies from the lock file
        entry: uv sync
        language: system
        pass_filenames: false
        stages: [post-checkout, post-merge]
        always_run: true
      - id: uv-lock-check
        name: uv-lock-check
        description: validate UV config and dependency lock file
        entry: uv lock --check
        language: system
        pass_filenames: false
        files: ^(.*/)?(pyproject\.toml|uv\.lock)$
      - id: ruff-lint
        name: ruff-lint
        entry: ruff check
        args:
          [
            --force-exclude,
            --config,
            pyproject.toml,
            --fix,
            --show-fixes,
            --exit-non-zero-on-fix,
          ]
        language: system
        types_or: [python]
        require_serial: true # run once for all files
      - id: ruff-format
        name: ruff-format
        entry: uv run --frozen ruff format
        args: [--force-exclude, --config, pyproject.toml]
        language: system
        types_or: [python]
        require_serial: true # run once for all files
      - id: pyright
        name: pyright
        entry: uv run --frozen pyright
        language: system
        types: [python]
        require_serial: true # run once for all files
